import { SpecializedModel } from "@/types/AiModel";

//TODO: Add the endpoint of each model

export const GEMINI_MODELS: SpecializedModel[] = [
    // ========================================================================
    // 2. GOOGLE GEMINI
    // ========================================================================
    
    // Reasoning Models
    //* Gemini 3 Pro Preview
    {
        id: "gemini-3-pro-preview",
        category: "reasoning",
        provider: "Gemini",
        providerModelId: "gemini-3-pro-preview",
        name: "Gemini 3 Pro",
        description: "Fast, frontier-class performance with upgraded visual and spatial reasoning",
        premium: false,
        enabled: true,
        icon: {
            light: "/icons/gemini.svg",
            dark: "/icons/gemini.svg",
        },
        providerMetadata: {
            provider: "Gemini",
            metadata: {
                contextWindow: 1048576,
                maxOutputTokens: 65536,
                knowledgeCutoff: "January 2025",
                latestUpdate: "November 2025",
                inputModalities: ["text", "image", "video", "audio", "pdf"],
                outputModalities: ["text"],
                capabilities: {
                    audioGeneration: false,
                    imageGeneration: false,
                    videoGeneration: false,
                    batchAPI: true,
                    caching: true,
                    liveAPI: false,
                    thinking: true,
                    structuredOutputs: true,
                },
                tools: {
                    googleSearch: true,
                    googleMaps: false,
                    codeExecution: true,
                    urlContext: true,
                    computerUse: false,
                    fileSearch: true,
                    functionCalling: true,
                },
                agents: {
                    deepResearch: false,
                },
            },
        },
    },
    //* Gemini 3 Flash Preview
    {
        id: "gemini-3-flash-preview",
        category: "reasoning",
        provider: "Gemini",
        providerModelId: "gemini-3-flash-preview",
        name: "Gemini 3 Flash",
        description: "Fast, frontier-class performance with upgraded visual and spatial reasoning",
        premium: false,
        enabled: true,
        icon: {
            light: "/icons/gemini.svg",
            dark: "/icons/gemini.svg",
        },
        providerMetadata: {
            provider: "Gemini",
            metadata: {
                contextWindow: 1048576,
                maxOutputTokens: 65536,
                knowledgeCutoff: "January 2025",
                latestUpdate: "December 2025",
                inputModalities: ["text", "image", "video", "audio", "pdf"],
                outputModalities: ["text"],
                capabilities: {
                    audioGeneration: false,
                    imageGeneration: false,
                    videoGeneration: false,
                    batchAPI: true,
                    caching: true,
                    liveAPI: false,
                    thinking: true,
                    structuredOutputs: true,
                },
                tools: {
                    googleSearch: true,
                    googleMaps: false,
                    codeExecution: true,
                    urlContext: true,
                    computerUse: false,
                    fileSearch: true,
                    functionCalling: true,
                },
                agents: {
                    deepResearch: false,
                },
            },
        },
    },
    //* Gemini 2.5 Flash
    {
        id: "gemini-2.5-flash",
        category: "reasoning",
        provider: "Gemini",
        providerModelId: "gemini-2.5-flash",
        name: "Gemini 2.5 Flash",
        description: "Stable, fast model with Google Maps grounding support",
        premium: false,
        enabled: true,
        icon: {
            light: "/icons/gemini.svg",
            dark: "/icons/gemini.svg",
        },
        providerMetadata: {
            provider: "Gemini",
            metadata: {
                contextWindow: 1048576,
                maxOutputTokens: 65536,
                knowledgeCutoff: "January 2025",
                latestUpdate: "June 2025",
                inputModalities: ["text", "image", "video", "audio"],
                outputModalities: ["text"],
                capabilities: {
                    audioGeneration: false,
                    imageGeneration: false,
                    videoGeneration: false,
                    batchAPI: true,
                    caching: true,
                    liveAPI: false,
                    thinking: true,
                    structuredOutputs: true,
                },
                tools: {
                    googleSearch: true,
                    googleMaps: true, // Supported
                    codeExecution: true,
                    urlContext: true,
                    computerUse: false,
                    fileSearch: true,
                    functionCalling: true,
                },
                agents: {
                    deepResearch: false,
                },
            },
        },
    },
    //* Gemini 2.5 Flash Preview
    {
        id: "gemini-2.5-flash-preview-09-2025",
        category: "reasoning",
        provider: "Gemini",
        providerModelId: "gemini-2.5-flash-preview-09-2025",
        name: "Gemini 2.5 Flash Preview",
        description: "Preview version of Gemini 2.5 Flash with latest updates",
        premium: false,
        enabled: true,
        icon: {
            light: "/icons/gemini.svg",
            dark: "/icons/gemini.svg",
        },
        providerMetadata: {
            provider: "Gemini",
            metadata: {
                contextWindow: 1048576,
                maxOutputTokens: 65536,
                knowledgeCutoff: "January 2025",
                latestUpdate: "September 2025",
                inputModalities: ["text", "image", "video", "audio"],
                outputModalities: ["text"],
                capabilities: {
                    audioGeneration: false,
                    imageGeneration: false,
                    videoGeneration: false,
                    batchAPI: true,
                    caching: true,
                    liveAPI: false,
                    thinking: true,
                    structuredOutputs: true,
                },
                tools: {
                    googleSearch: true,
                    googleMaps: false, // Not supported in this preview
                    codeExecution: true,
                    urlContext: true,
                    computerUse: false,
                    fileSearch: true,
                    functionCalling: true,
                },
                agents: {
                    deepResearch: false,
                },
            },
        },
    },
    //* Gemini 2.5 Flash Lite
    {
        id: "gemini-2.5-flash-lite",
        category: "reasoning",
        provider: "Gemini",
        providerModelId: "gemini-2.5-flash-lite",
        name: "Gemini 2.5 Flash Lite",
        description: "Stable, cost-efficient model with Google Maps grounding support",
        premium: false,
        enabled: true,
        icon: {
            light: "/icons/gemini.svg",
            dark: "/icons/gemini.svg",
        },
        providerMetadata: {
            provider: "Gemini",
            metadata: {
                contextWindow: 1048576,
                maxOutputTokens: 65536,
                knowledgeCutoff: "January 2025",
                latestUpdate: "July 2025",
                inputModalities: ["text", "image", "video", "audio", "pdf"],
                outputModalities: ["text"],
                capabilities: {
                    audioGeneration: false,
                    imageGeneration: false,
                    videoGeneration: false,
                    batchAPI: true,
                    caching: true,
                    liveAPI: false,
                    thinking: true,
                    structuredOutputs: true,
                },
                tools: {
                    googleSearch: true,
                    googleMaps: true, // Supported
                    codeExecution: true,
                    urlContext: true,
                    computerUse: false,
                    fileSearch: true,
                    functionCalling: true,
                },
                agents: {
                    deepResearch: false,
                },
            },
        },
    },

    // Image Generation Models
    //* Gemini 3 Pro Image Preview (Nano Banana Pro)
    {
        id: "gemini-3-pro-image-preview",
        category: "image",
        provider: "Gemini",
        providerModelId: "gemini-3-pro-image-preview",
        name: "Nano Banana Pro",
        description: "Professional asset production with advanced reasoning and up to 4K resolution",
        premium: false,
        enabled: true,
        icon: {
            light: "/icons/gemini.svg",
            dark: "/icons/gemini.svg",
        },
        providerMetadata: {
            provider: "Gemini",
            metadata: {
                contextWindow: 65536,
                maxOutputTokens: 32768,
                knowledgeCutoff: "January 2025",
                latestUpdate: "November 2025",
                inputModalities: ["image", "text"],
                outputModalities: ["image", "text"],
                capabilities: {
                    audioGeneration: false,
                    imageGeneration: true,
                    videoGeneration: false,
                    batchAPI: true,
                    caching: false,
                    liveAPI: false,
                    thinking: true,
                    structuredOutputs: true,
                },
                tools: {
                    googleSearch: true,
                    googleMaps: false,
                    codeExecution: false,
                    urlContext: false,
                    computerUse: false,
                    fileSearch: false,
                    functionCalling: false,
                },
                agents: {
                    deepResearch: false,
                },
                imageGenerationOptions: {
                    modelName: "Nano Banana Pro",
                    supportsTextGeneration: true,
                    resolutionTiers: ["1K", "2K", "4K"],
                    aspectRatios: [
                        { ratio: "1:1", resolution: "1024x1024", tokens: 1120 },
                        { ratio: "1:1", resolution: "2048x2048", tokens: 1120 },
                        { ratio: "1:1", resolution: "4096x4096", tokens: 2000 },
                        { ratio: "16:9", resolution: "1376x768", tokens: 1120 },
                        { ratio: "16:9", resolution: "2752x1536", tokens: 1120 },
                        { ratio: "16:9", resolution: "5504x3072", tokens: 2000 },
                        { ratio: "9:16", resolution: "768x1376", tokens: 1120 },
                        { ratio: "9:16", resolution: "1536x2752", tokens: 1120 },
                        { ratio: "9:16", resolution: "3072x5504", tokens: 2000 },
                    ],
                },
            },
        },
    },
    //* Gemini 2.5 Flash Image (Nano Banana)
    {
        id: "gemini-2.5-flash-image",
        category: "image",
        provider: "Gemini",
        providerModelId: "gemini-2.5-flash-image",
        name: "Nano Banana",
        description: "Fast image generation optimized for high-volume, low-latency tasks",
        premium: false,
        enabled: true,
        icon: {
            light: "/icons/gemini.svg",
            dark: "/icons/gemini.svg",
        },
        providerMetadata: {
            provider: "Gemini",
            metadata: {
                contextWindow: 65536,
                maxOutputTokens: 32768,
                inputModalities: ["image", "text"],
                outputModalities: ["image", "text"],
                capabilities: {
                    audioGeneration: false,
                    imageGeneration: true,
                    videoGeneration: false,
                    batchAPI: true,
                    caching: false,
                    liveAPI: false,
                    thinking: true,
                    structuredOutputs: true,
                },
                tools: {
                    googleSearch: true,
                    googleMaps: false,
                    codeExecution: false,
                    urlContext: false,
                    computerUse: false,
                    fileSearch: false,
                    functionCalling: false,
                },
                agents: {
                    deepResearch: false,
                },
                imageGenerationOptions: {
                    modelName: "Nano Banana",
                    supportsTextGeneration: true,
                    aspectRatios: [
                        { ratio: "1:1", resolution: "1024x1024", tokens: 1290 },
                        { ratio: "2:3", resolution: "832x1248", tokens: 1290 },
                        { ratio: "3:2", resolution: "1248x832", tokens: 1290 },
                        { ratio: "16:9", resolution: "1344x768", tokens: 1290 },
                        { ratio: "9:16", resolution: "768x1344", tokens: 1290 },
                        { ratio: "21:9", resolution: "1536x672", tokens: 1290 },
                    ],
                },
            },
        },
    },
    
    // Video Generation Models
    //* VEO 3.1 Generate Preview
    {
        id: "veo-3.1-generate-preview",
        category: "video",
        provider: "Gemini",
        providerModelId: "veo-3.1-generate-preview",
        name: "Veo 3.1",
        description: "State-of-the-art video generation with reference images support",
        premium: true,
        enabled: true,
        icon: {
            light: "/icons/gemini.svg",
            dark: "/icons/gemini.svg",
        },
        providerMetadata: {
            provider: "Gemini",
            metadata: {
                contextWindow: 0,
                maxOutputTokens: 0,
                inputModalities: ["text", "image", "video"],
                outputModalities: ["video"],
                capabilities: {
                    audioGeneration: false,
                    imageGeneration: false,
                    videoGeneration: true,
                    batchAPI: false,
                    caching: false,
                    liveAPI: false,
                    thinking: false,
                    structuredOutputs: false,
                },
                tools: {
                    googleSearch: false,
                    googleMaps: false,
                    codeExecution: false,
                    urlContext: false,
                    computerUse: false,
                    fileSearch: false,
                    functionCalling: false,
                },
                agents: {
                    deepResearch: false,
                },
                videoGenerationOptions: {
                    modelName: "Veo 3.1",
                    aspectRatios: ["16:9", "9:16"],
                    resolutions: ["720p", "1080p"],
                    durationSeconds: [4, 6, 8],
                    features: {
                        textToVideo: true,
                        imageToVideo: true,
                        videoExtension: true,
                        interpolation: true,
                        referenceImages: true,
                        audioCues: true,
                        negativePrompt: true,
                    },
                    personGeneration: ["allow_adult"],
                },
            },
        },
        metadata: {
            qualityResolutions: ["720p", "1080p"],
            aspectRatios: ["16:9", "9:16"],
            maxDuration: 8,
            supportedFormats: ["mp4", "webm"],
        },
    },
    //* VEO 3.1 Fast Generate Preview
    {
        id: "veo-3.1-fast-generate-preview",
        category: "video",
        provider: "Gemini",
        providerModelId: "veo-3.1-fast-generate-preview",
        name: "Veo 3.1 Fast",
        description: "Fast video generation with all Veo 3.1 features",
        premium: true,
        enabled: true,
        icon: {
            light: "/icons/gemini.svg",
            dark: "/icons/gemini.svg",
        },
        providerMetadata: {
            provider: "Gemini",
            metadata: {
                contextWindow: 0,
                maxOutputTokens: 0,
                inputModalities: ["text", "image", "video"],
                outputModalities: ["video"],
                capabilities: {
                    audioGeneration: false,
                    imageGeneration: false,
                    videoGeneration: true,
                    batchAPI: false,
                    caching: false,
                    liveAPI: false,
                    thinking: false,
                    structuredOutputs: false,
                },
                tools: {
                    googleSearch: false,
                    googleMaps: false,
                    codeExecution: false,
                    urlContext: false,
                    computerUse: false,
                    fileSearch: false,
                    functionCalling: false,
                },
                agents: {
                    deepResearch: false,
                },
                videoGenerationOptions: {
                    modelName: "Veo 3.1 Fast",
                    aspectRatios: ["16:9", "9:16"],
                    resolutions: ["720p", "1080p"],
                    durationSeconds: [4, 6, 8],
                    features: {
                        textToVideo: true,
                        imageToVideo: true,
                        videoExtension: true,
                        interpolation: true,
                        referenceImages: true,
                        audioCues: true,
                        negativePrompt: true,
                    },
                    personGeneration: ["allow_adult"],
                },
            },
        },
        metadata: {
            qualityResolutions: ["720p", "1080p"],
            aspectRatios: ["16:9", "9:16"],
            maxDuration: 8,
            supportedFormats: ["mp4", "webm"],
        },
    },
];
