import { SpecializedModel } from "@/types/AiModel";

export const OPENAI_MODELS: SpecializedModel[] = [
    // ========================================================================
    // 1. OPENAI (GPT)
    // ========================================================================
    
    // Reasoning Models
    //*Gpt 5.2
    {
        id: "gpt-5.2",
        category: "reasoning",
        provider: "GPT",
        providerModelId: "gpt-5.2",
        name: "GPT-5.2",
        description: "The best model for coding and agentic tasks across industries",
        premium: false,
        enabled: true,
        icon: {
            light: "/icons/gpt-claro.svg",
            dark: "/icons/gpt-oscuro.svg",
        },
        providerMetadata: {
            provider: "GPT",
            metadata: {
                contextWindow: 400000,
                maxOutputTokens: 128000,
                knowledgeCutoff: "Aug 31, 2025",
                inputModalities: ["text", "image"],
                outputModalities: ["text"],
                endpoints: {
                    chatCompletions: true,
                    responses: true,
                    realtime: false,
                    assistants: false,
                    batch: true,
                    fineTuning: false,
                    embeddings: false,
                    imageGeneration: false,
                    videos: false,
                    imageEdit: false,
                    speechGeneration: false,
                    transcription: false,
                    translation: false,
                    moderation: false,
                },
                features: {
                    streaming: true,
                    functionCalling: true,
                    structuredOutputs: true,
                    fineTuning: false,
                    distillation: true,
                },
                tools: {
                    webSearch: true,
                    fileSearch: true,
                    imageGeneration: true,
                    codeInterpreter: true,
                    computerUse: false,
                    mcp: true,
                },
                snapshots: ["gpt-5.2", "gpt-5.2-2025-12-11"],
                pricing: {
                    inputPerMillion: 1.75,
                    cachedInputPerMillion: 0.175,
                    outputPerMillion: 14.00,
                },
            },
        },
    },
    //*Gpt 5.2 pro
    {
        id: "gpt-5.2-pro",
        category: "reasoning",
        provider: "GPT",
        providerModelId: "gpt-5.2-pro",
        name: "GPT-5.2 Pro",
        description: "Version of GPT-5.2 that produces smarter and more precise responses.",
        premium: false,
        enabled: true,
        icon: {
            light: "/icons/gpt-claro.svg",
            dark: "/icons/gpt-oscuro.svg",
        },
        providerMetadata: {
            provider: "GPT",
            metadata: {
                contextWindow: 400000,
                maxOutputTokens: 128000,
                knowledgeCutoff: "Aug 31, 2025",
                inputModalities: ["text", "image"],
                outputModalities: ["text"],
                endpoints: {
                    chatCompletions: false,
                    responses: true,
                    realtime: false,
                    assistants: false,
                    batch: false,
                    fineTuning: false,
                    embeddings: false,
                    imageGeneration: false,
                    videos: false,
                    imageEdit: false,
                    speechGeneration: false,
                    transcription: false,
                    translation: false,
                    moderation: false,
                },
                features: {
                    streaming: true,
                    functionCalling: true,
                    structuredOutputs: false,
                    fineTuning: false,
                    distillation: false,
                },
                tools: {
                    webSearch: true,
                    fileSearch: true,
                    imageGeneration: true,
                    codeInterpreter: false,
                    computerUse: false,
                    mcp: true,
                },
                snapshots: ["gpt-5.2-pro", "gpt-5.2-pro-2025-12-11"],
                pricing: {
                    inputPerMillion: 21.00,
                    outputPerMillion: 168.00,
                },
            },
        },
    },
    //*Gpt 5
    {
        id: "gpt-5",
        category: "reasoning",
        provider: "GPT",
        providerModelId: "gpt-5",
        name: "GPT-5",
        description: "Previous intelligent reasoning model for coding and agentic tasks with configurable reasoning effort",
        premium: false,
        enabled: true,
        icon: {
            light: "/icons/gpt-claro.svg",
            dark: "/icons/gpt-oscuro.svg",
        },
        providerMetadata: {
            provider: "GPT",
            metadata: {
                contextWindow: 400000,
                maxOutputTokens: 128000,
                knowledgeCutoff: "Sep 30, 2024",
                inputModalities: ["text", "image"],
                outputModalities: ["text"],
                endpoints: {
                    chatCompletions: true,
                    responses: true,
                    realtime: false,
                    assistants: false,
                    batch: true,
                    fineTuning: false,
                    embeddings: false,
                    imageGeneration: false,
                    videos: false,
                    imageEdit: false,
                    speechGeneration: false,
                    transcription: false,
                    translation: false,
                    moderation: false,
                },
                features: {
                    streaming: true,
                    functionCalling: true,
                    structuredOutputs: true,
                    fineTuning: false,
                    distillation: true,
                },
                tools: {
                    webSearch: true,
                    fileSearch: true,
                    imageGeneration: true,
                    codeInterpreter: true,
                    computerUse: false,
                    mcp: true,
                },
                snapshots: ["gpt-5", "gpt-5-2025-08-07"],
                pricing: {
                    inputPerMillion: 1.25,
                    cachedInputPerMillion: 0.125,
                    outputPerMillion: 10.00,
                },
            },
        },
    },
    //*Gpt 5 mini
    {
        id: "gpt-5-mini",
        category: "reasoning",
        provider: "GPT",
        providerModelId: "gpt-5-mini",
        name: "GPT-5 mini",
        description: "A faster, cost-efficient version of GPT-5 for well-defined tasks",
        premium: false,
        enabled: true,
        icon: {
            light: "/icons/gpt-claro.svg",
            dark: "/icons/gpt-oscuro.svg",
        },
        providerMetadata: {
            provider: "GPT",
            metadata: {
                contextWindow: 400000,
                maxOutputTokens: 128000,
                knowledgeCutoff: "May 31, 2024",
                inputModalities: ["text", "image"],
                outputModalities: ["text"],
                endpoints: {
                    chatCompletions: true,
                    responses: true,
                    realtime: false,
                    assistants: false,
                    batch: true,
                    fineTuning: false,
                    embeddings: false,
                    imageGeneration: false,
                    videos: false,
                    imageEdit: false,
                    speechGeneration: false,
                    transcription: false,
                    translation: false,
                    moderation: false,
                },
                features: {
                    streaming: true,
                    functionCalling: true,
                    structuredOutputs: true,
                    fineTuning: false,
                    distillation: false,
                },
                tools: {
                    webSearch: true,
                    fileSearch: true,
                    imageGeneration: false,
                    codeInterpreter: true,
                    computerUse: false,
                    mcp: true,
                },
                snapshots: ["gpt-5-mini", "gpt-5-mini-2025-08-07"],
                pricing: {
                    inputPerMillion: 0.25,
                    cachedInputPerMillion: 0.025,
                    outputPerMillion: 2.00,
                },
            },
        },
    },
    //*Gpt 5 nano
    {
        id: "gpt-5-nano",
        category: "reasoning",
        provider: "GPT",
        providerModelId: "gpt-5-nano",
        name: "GPT-5 nano",
        description: "Fastest, most cost-efficient version of GPT-5",
        premium: false,
        enabled: true,
        icon: {
            light: "/icons/gpt-claro.svg",
            dark: "/icons/gpt-oscuro.svg",
        },
        providerMetadata: {
            provider: "GPT",
            metadata: {
                contextWindow: 400000,
                maxOutputTokens: 128000,
                knowledgeCutoff: "May 31, 2024",
                inputModalities: ["text", "image"],
                outputModalities: ["text"],
                endpoints: {
                    chatCompletions: true,
                    responses: true,
                    realtime: false,
                    assistants: false,
                    batch: true,
                    fineTuning: false,
                    embeddings: false,
                    imageGeneration: false,
                    videos: false,
                    imageEdit: false,
                    speechGeneration: false,
                    transcription: false,
                    translation: false,
                    moderation: false,
                },
                features: {
                    streaming: true,
                    functionCalling: true,
                    structuredOutputs: true,
                    fineTuning: false,
                    distillation: false,
                },
                tools: {
                    webSearch: true,
                    fileSearch: true,
                    imageGeneration: true,
                    codeInterpreter: true,
                    computerUse: false,
                    mcp: true,
                },
                snapshots: ["gpt-5-nano", "gpt-5-nano-2025-08-07"],
                pricing: {
                    inputPerMillion: 0.05,
                    cachedInputPerMillion: 0.005,
                    outputPerMillion: 0.40,
                },
            },
        },
    },
    //*Gpt 4.1
    {
        id: "gpt-4-1",
        category: "reasoning",
        provider: "GPT",
        providerModelId: "gpt-4-1",
        name: "GPT-4-1",
        description: "Smartest non-reasoning model",
        premium: false,
        enabled: true,
        icon: {
            light: "/icons/gpt-claro.svg",
            dark: "/icons/gpt-oscuro.svg",
        },
        providerMetadata: {
            provider: "GPT",
            metadata: {
                contextWindow: 1047576,
                maxOutputTokens: 32768,
                knowledgeCutoff: "Jun 01, 2024",
                inputModalities: ["text", "image"],
                outputModalities: ["text"],
                endpoints: {
                    chatCompletions: true,
                    responses: true,
                    realtime: false,
                    assistants: true,
                    batch: true,
                    fineTuning: true,
                    embeddings: false,
                    imageGeneration: false,
                    videos: false,
                    imageEdit: false,
                    speechGeneration: false,
                    transcription: false,
                    translation: false,
                    moderation: false,
                },
                features: {
                    streaming: true,
                    functionCalling: true,
                    structuredOutputs: true,
                    fineTuning: true,
                    distillation: true,
                },
                tools: {
                    webSearch: true,
                    fileSearch: true,
                    imageGeneration: true,
                    codeInterpreter: true,
                    computerUse: false,
                    mcp: true,
                },
                snapshots: ["gpt-4-1", "gpt-4.1-2025-04-14"],
                pricing: {
                    inputPerMillion: 2.00,
                    cachedInputPerMillion: 0.50,
                    outputPerMillion: 8.00,
                },
            },
        },
    },

    // VIDEO Models
    //* Sora 2
    {
        id: "sora-2",
        category: "video",
        provider: "GPT",
        providerModelId: "sora-2",
        name: "Sora 2",
        description: "Flagship video generation with synced audio - richly detailed, dynamic clips from text or images",
        premium: true,
        enabled: true,
        icon: {
            light: "/icons/gpt-claro.svg",
            dark: "/icons/gpt-oscuro.svg",
        },
        providerMetadata: {
            provider: "GPT",
            metadata: {
                contextWindow: 0,
                maxOutputTokens: 0,
                knowledgeCutoff: "May 31, 2024",
                inputModalities: ["text", "image"],
                outputModalities: ["video", "audio"],
                endpoints: {
                    chatCompletions: false,
                    responses: false,
                    realtime: false,
                    assistants: false,
                    batch: true,
                    fineTuning: false,
                    embeddings: false,
                    imageGeneration: false,
                    videos: true,
                    imageEdit: false,
                    speechGeneration: false,
                    transcription: false,
                    translation: false,
                    moderation: false,
                },
                snapshots: ["sora-2", "sora-2-2025-10-06", "sora-2-2025-12-08"],
                pricing: {
                    inputPerMillion: 0,
                    outputPerMillion: 0,
                    videoGenerationPerSecond: 0.10, // $0.10 per second
                },
                videoGenerationOptions: {
                    aspectRatios: ["720x1280", "1280x720"], // Portrait and Landscape
                    resolutions: ["720p"],
                    maxDuration: 60, // Assuming max 60 seconds based on typical limits
                    audioGeneration: true, // Sora 2 generates synced audio
                    snapshots: ["sora-2", "sora-2-2025-10-06", "sora-2-2025-12-08"],
                },
            },
        },
        metadata: {
            aspectRatios: ["720x1280", "1280x720"],
            maxDuration: 60,
            supportedFormats: ["mp4"],
        },
    },
    //* Sora 2 Pro
    {
        id: "sora-2-pro",
        category: "video",
        provider: "GPT",
        providerModelId: "sora-2-pro",
        name: "Sora 2 Pro",
        description: "Most advanced synced-audio video generation - state-of-the-art quality with higher resolutions",
        premium: true,
        enabled: true,
        icon: {
            light: "/icons/gpt-claro.svg",
            dark: "/icons/gpt-oscuro.svg",
        },
        providerMetadata: {
            provider: "GPT",
            metadata: {
                contextWindow: 0,
                maxOutputTokens: 0,
                inputModalities: ["text", "image"],
                outputModalities: ["video", "audio"],
                endpoints: {
                    chatCompletions: false,
                    responses: false,
                    realtime: false,
                    assistants: false,
                    batch: false,
                    fineTuning: false,
                    embeddings: false,
                    imageGeneration: false,
                    videos: true,
                    imageEdit: false,
                    speechGeneration: false,
                    transcription: false,
                    translation: false,
                    moderation: false,
                },
                snapshots: ["sora-2-pro", "sora-2-pro-2025-10-06"],
                pricing: {
                    inputPerMillion: 0,
                    outputPerMillion: 0,
                    // Resolution-based pricing tiers
                    videoGenerationPerSecond: {
                        "720p": 0.30,  // $0.30/sec for Portrait: 720x1280, Landscape: 1280x720
                        "1080p": 0.50, // $0.50/sec for Portrait: 1024x1792, Landscape: 1792x1024
                    },
                },
                videoGenerationOptions: {
                    aspectRatios: ["720x1280", "1280x720", "1024x1792", "1792x1024"],
                    resolutions: ["720p", "1080p"],
                    maxDuration: 60,
                    audioGeneration: true,
                    snapshots: ["sora-2-pro", "sora-2-pro-2025-10-06"],
                },
            },
        },
        metadata: {
            aspectRatios: ["720x1280", "1280x720", "1024x1792", "1792x1024"],
            maxDuration: 60,
            supportedFormats: ["mp4"],
        },
    },

    //IMAGE Models
    //* GPT Image 1.5
    {
        id: "gpt-image-1.5",
        category: "image",
        provider: "GPT",
        providerModelId: "gpt-image-1.5",
        name: "GPT Image 1.5",
        description: "State-of-the-art image generation model with better instruction following and adherence to prompts",
        premium: false,
        enabled: true,
        icon: {
            light: "/icons/gpt-claro.svg",
            dark: "/icons/gpt-oscuro.svg",
        },
        providerMetadata: {
            provider: "GPT",
            metadata: {
                contextWindow: 0,
                maxOutputTokens: 0,
                inputModalities: ["text", "image"],
                outputModalities: ["image", "text"],
                endpoints: {
                    chatCompletions: true,
                    responses: true,
                    realtime: true,
                    assistants: true,
                    batch: true,
                    fineTuning: false,
                    embeddings: false,
                    imageGeneration: true,
                    videos: false,
                    imageEdit: true,
                    speechGeneration: false,
                    transcription: false,
                    translation: false,
                    moderation: false,
                },
                features: {
                    streaming: false,
                    functionCalling: false,
                    structuredOutputs: false,
                    fineTuning: false,
                    distillation: false,
                },
                snapshots: ["gpt-image-1.5", "gpt-image-1.5-2025-12-16"],
                pricing: {
                    inputPerMillion: 5.00,
                    cachedInputPerMillion: 1.25,
                    outputPerMillion: 10.00,
                    imageGenerationPerImage: {
                        Low: {
                            "1024x1024": 0.009,
                            "1024x1536": 0.013,
                            "1536x1024": 0.013,
                        },
                        Medium: {
                            "1024x1024": 0.034,
                            "1024x1536": 0.05,
                            "1536x1024": 0.05,
                        },
                        High: {
                            "1024x1024": 0.133,
                            "1024x1536": 0.20,
                            "1536x1024": 0.20,
                        },
                    },
                },
                imageGenerationOptions: {
                    modelType: "gpt-image",
                    sizes: ["1024x1024", "1024x1536", "1536x1024"],
                    quality: ["low", "medium", "high", "auto"],
                    background: ["transparent", "opaque", "auto"],
                    output_format: ["png", "jpeg", "webp"],
                    n: [1, 2, 3, 4],
                    moderation: ["low", "auto"],
                },
            },
        },
        metadata: {
            qualityResolutions: ["Low", "Medium", "High"],
            aspectRatios: ["1024x1024", "1024x1536", "1536x1024"],
            supportedFormats: ["png", "jpg"],
        },
    },
    //* GPT Image 1
    {
        id: "gpt-image-1",
        category: "image",
        provider: "GPT",
        providerModelId: "gpt-image-1",
        name: "GPT Image 1",
        description: "Previous image generation model with higher quality but slower speed",
        premium: false,
        enabled: true,
        icon: {
            light: "/icons/gpt-claro.svg",
            dark: "/icons/gpt-oscuro.svg",
        },
        providerMetadata: {
            provider: "GPT",
            metadata: {
                contextWindow: 0,
                maxOutputTokens: 0,
                inputModalities: ["text", "image"],
                outputModalities: ["image"],
                endpoints: {
                    chatCompletions: true,
                    responses: true,
                    realtime: true,
                    assistants: true,
                    batch: true,
                    fineTuning: false,
                    embeddings: false,
                    imageGeneration: true,
                    videos: false,
                    imageEdit: true,
                    speechGeneration: false,
                    transcription: false,
                    translation: false,
                    moderation: false,
                },
                features: {
                    streaming: false,
                    functionCalling: false,
                    structuredOutputs: false,
                    fineTuning: false,
                    distillation: false,
                },
                snapshots: ["gpt-image-1"],
                pricing: {
                    inputPerMillion: 5.00,
                    cachedInputPerMillion: 1.25,
                    outputPerMillion: 40.00,
                    imageGenerationPerImage: {
                        Low: {
                            "1024x1024": 0.011,
                            "1024x1536": 0.016,
                            "1536x1024": 0.016,
                        },
                        Medium: {
                            "1024x1024": 0.042,
                            "1024x1536": 0.063,
                            "1536x1024": 0.063,
                        },
                        High: {
                            "1024x1024": 0.167,
                            "1024x1536": 0.25,
                            "1536x1024": 0.25,
                        },
                    },
                },
                imageGenerationOptions: {
                    modelType: "gpt-image",
                    sizes: ["1024x1024", "1024x1536", "1536x1024"],
                    quality: ["low", "medium", "high", "auto"],
                    background: ["transparent", "opaque", "auto"],
                    output_format: ["png", "jpeg", "webp"],
                    n: [1, 2, 3, 4],
                    moderation: ["low", "auto"],
                },
            },
        },
        metadata: {
            qualityResolutions: ["Low", "Medium", "High"],
            aspectRatios: ["1024x1024", "1024x1536", "1536x1024"],
            supportedFormats: ["png", "jpg"],
        },
    },
    //* GPT Image 1 Mini
    {
        id: "gpt-image-1-mini",
        category: "image",
        provider: "GPT",
        providerModelId: "gpt-image-1-mini",
        name: "GPT Image 1 Mini",
        description: "Cost-efficient version of GPT Image 1 with lower pricing",
        premium: false,
        enabled: true,
        icon: {
            light: "/icons/gpt-claro.svg",
            dark: "/icons/gpt-oscuro.svg",
        },
        providerMetadata: {
            provider: "GPT",
            metadata: {
                contextWindow: 0,
                maxOutputTokens: 0,
                inputModalities: ["text", "image"],
                outputModalities: ["image"],
                endpoints: {
                    chatCompletions: true,
                    responses: true,
                    realtime: true,
                    assistants: true,
                    batch: true,
                    fineTuning: false,
                    embeddings: false,
                    imageGeneration: true,
                    videos: false,
                    imageEdit: true,
                    speechGeneration: false,
                    transcription: false,
                    translation: false,
                    moderation: false,
                },
                features: {
                    streaming: false,
                    functionCalling: false,
                    structuredOutputs: false,
                    fineTuning: false,
                    distillation: false,
                },
                snapshots: ["gpt-image-1-mini"],
                pricing: {
                    inputPerMillion: 2.00,
                    cachedInputPerMillion: 0.20,
                    outputPerMillion: 8.00,
                    imageGenerationPerImage: {
                        Low: {
                            "1024x1024": 0.005,
                            "1024x1536": 0.006,
                            "1536x1024": 0.006,
                        },
                        Medium: {
                            "1024x1024": 0.011,
                            "1024x1536": 0.015,
                            "1536x1024": 0.015,
                        },
                        High: {
                            "1024x1024": 0.036,
                            "1024x1536": 0.052,
                            "1536x1024": 0.052,
                        },
                    },
                },
                imageGenerationOptions: {
                    modelType: "gpt-image",
                    sizes: ["1024x1024", "1024x1536", "1536x1024"],
                    quality: ["low", "medium", "high", "auto"],
                    background: ["transparent", "opaque", "auto"],
                    output_format: ["png", "jpeg", "webp"],
                    n: [1, 2, 3, 4],
                    moderation: ["low", "auto"],
                },
            },
        },
        metadata: {
            qualityResolutions: ["Low", "Medium", "High"],
            aspectRatios: ["1024x1024", "1024x1536", "1536x1024"],
            supportedFormats: ["png", "jpg"],
        },
    },
    //* DALL-E 3
    {
        id: "dall-e-3",
        category: "image",
        provider: "GPT",
        providerModelId: "dall-e-3",
        name: "DALL-E 3",
        description: "The latest DALL·E model that understands significantly more nuance and detail than previous systems",
        premium: true,
        enabled: true,
        icon: {
            light: "/icons/gpt-claro.svg",
            dark: "/icons/gpt-oscuro.svg",
        },
        providerMetadata: {
            provider: "GPT",
            metadata: {
                contextWindow: 0,
                maxOutputTokens: 0,
                inputModalities: ["text"],
                outputModalities: ["image"],
                endpoints: {
                    chatCompletions: false,
                    responses: false,
                    realtime: false,
                    assistants: false,
                    batch: false,
                    fineTuning: false,
                    embeddings: false,
                    imageGeneration: true,
                    videos: false,
                    imageEdit: false,
                    speechGeneration: false,
                    transcription: false,
                    translation: false,
                    moderation: false,
                },
                snapshots: ["dall-e-3"],
                pricing: {
                    inputPerMillion: 0,
                    outputPerMillion: 0,
                    imageGenerationPerImage: {
                        High: {
                            "1024x1024": 0.04,
                            "1024x1792": 0.08,
                            "1792x1024": 0.08,
                        },
                    },
                },
                imageGenerationOptions: {
                    modelType: "dalle",
                    sizes: ["1024x1024", "1024x1792", "1792x1024"],
                    quality: ["standard", "hd"],
                    n: [1],
                },
            },
        },
        metadata: {
            qualityResolutions: ["Standard", "HD"],
            aspectRatios: ["1024x1024", "1024x1792", "1792x1024"],
            supportedFormats: ["png"],
        },
    },
];
